CoordError: 1) added to provide notification when SonTek data is loaded using other than earth coordinates UMeasQ: 1) added stacked bar graph for displaying measured discharge uncertainty_bottom_discharge UMeasurement: 1) added stacked bar graph for displaying uncertainty contributions from all sources Oursin: 1) rearranged columns in data frame, 2) normalized rectangular law by absolute value of total discharge QRev_Users.docx: 1) fixed text that referred to ensembles instead of depth cells in water track filters QRev: 1) added code for uncertainty graphics, 2) rearranged uncertainty table columns WTFilters: 1) change SNR label to SNR Range (dB)